# Generated by Django 2.1 on 2018-08-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('base', models.CharField(blank=True, max_length=255, null=True)),
                ('symbol', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('volumeDay', models.IntegerField(default=0, null=True)),
                ('telegram', models.IntegerField(default=0, null=True)),
                ('highDay', models.IntegerField(default=0, null=True)),
                ('priceChangeRateDay', models.IntegerField(default=0, null=True)),
                ('type', models.IntegerField(default=0, null=True)),
                ('PriceChageDay', models.IntegerField(default=0, null=True)),
                ('lowDay', models.IntegerField(default=0, null=True)),
                ('price', models.IntegerField(default=0, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('pair', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(null=True)),
            ],
            options={
                'db_table': 'coins',
            },
        ),
    ]
