# Generated by Django 2.1 on 2018-08-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coins',
            old_name='PriceChageDay',
            new_name='priceChangeDay',
        ),
    ]
