# Generated by Django 2.1 on 2018-08-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20180816_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='coins',
            name='decimals',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
