# Generated by Django 2.1 on 2018-08-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0003_coins_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
