# Generated by Django 2.0 on 2018-07-23 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegramtoken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtoken',
            name='administrator',
            field=models.ForeignKey(default=1, help_text='Wallet-ID of licensor. By default the stream publisher Wallet-ID is assumed to be the licensor. This assumption can be overridden by providing an explicit list of one or more Wallet-IDs. Future extensibility: licensor_identifier_type.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Telegram Administrator'),
            preserve_default=False,
        ),
    ]
