# Generated by Django 2.0 on 2018-07-23 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegramtoken', '0002_telegramtoken_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='A valid blockchain wallet address.', max_length=60, verbose_name='Wallet-ID')),
                ('memo', models.CharField(blank=True, help_text='Short internal note about this address.', max_length=255, verbose_name='Internal Memo')),
            ],
            options={
                'verbose_name_plural': 'Wallet-IDs',
                'verbose_name': 'Wallet-ID',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='walletid',
        ),
        migrations.AddField(
            model_name='walletid',
            name='owner',
            field=models.ForeignKey(help_text='Owner of Wallet-ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
