# Generated by Django 2.0 on 2018-07-23 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegramtoken', '0003_auto_20180723_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramtoken',
            name='administrator',
            field=models.ForeignKey(help_text='Wallet-ID of Administrator. By default the stream publisher Wallet-ID is assumed to be the licensor. This assumption can be overridden by providing an explicit list of one or more Wallet-IDs. Future extensibility: licensor_identifier_type.', on_delete=django.db.models.deletion.CASCADE, to='telegramtoken.WalletID', verbose_name='Telegram Administrator'),
        ),
    ]
