# Generated by Django 2.0.7 on 2018-07-24 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_field_fix_and_editable'),
        ('telegramtoken', '0005_auto_20180723_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramtoken',
            name='organization',
            field=models.ForeignKey(default=1, help_text='Organization assigned to this Telegram Token', on_delete=django.db.models.deletion.CASCADE, to='organizations.OrganizationUser', verbose_name='Telegram Organization'),
            preserve_default=False,
        ),
    ]
